service: evaluacion-gpo-modelo

frameworkVersion: '2'

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000
  country: ${opt:country}
  stage: ${opt:stage, 'dev'}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${self:custom.stage}
  region: us-west-2
  deploymentBucket:
    name: ${self:custom.stage}-carrg-deployments
    blockPublicAccess: true
  environment:
    BASE_URL: ${env:BASE_URL}
  # apiKeys:
  #   - free:
  #       - ${opt:stage}-carrg
  # usagePlan:
  #   - free:
  #       quota:
  #         limit: 10
  #         offset: 0
  #         period: MONTH
  #       throttle:
  #         burstLimit: 5
  #         rateLimit: 5
  apiGateway:
    shouldStartNameWithService: true

functions:
  get_order_by_power:
    handler: src/get_order_by_power/handler.main
    description: Obtiene lista de personajes con mayor poder
    events:
     - http:
         path: characters/get-order_by_power
         method: post
         private: true

  get-character-winner:
    handler: src/get_character_winner/handler.main
    description: Obtiene el personaje ganador
    events:
     - http:
         path: characters/get-winner
         method: post
         private: true

  get-character:
    handler: src/get_characters/handler.main
    description: Obtiene la lista de los personales
    events:
     - http:
         path: characters
         method: get
         private: true